// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: oms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_NEW        OrderStatus = 0
	OrderStatus_PROCESSING OrderStatus = 1
	OrderStatus_COMPLETED  OrderStatus = 2
	OrderStatus_CANCELLED  OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "NEW",
		1: "PROCESSING",
		2: "COMPLETED",
		3: "CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"NEW":        0,
		"PROCESSING": 1,
		"COMPLETED":  2,
		"CANCELLED":  3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_oms_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{0}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProductCode   string                 `protobuf:"bytes,3,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	CustomerCost  float64                `protobuf:"fixed64,4,opt,name=customer_cost,json=customerCost,proto3" json:"customer_cost,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_oms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *Product) GetCustomerCost() float64 {
	if x != nil {
		return x.CustomerCost
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProductCode   string                 `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	CustomerCost  float64                `protobuf:"fixed64,3,opt,name=customer_cost,json=customerCost,proto3" json:"customer_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_oms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *CreateRequest) GetCustomerCost() float64 {
	if x != nil {
		return x.CustomerCost
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ProductCode   *string                `protobuf:"bytes,3,opt,name=product_code,json=productCode,proto3,oneof" json:"product_code,omitempty"`
	CustomerCost  *float64               `protobuf:"fixed64,4,opt,name=customer_cost,json=customerCost,proto3,oneof" json:"customer_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_oms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRequest) GetProductCode() string {
	if x != nil && x.ProductCode != nil {
		return *x.ProductCode
	}
	return ""
}

func (x *UpdateRequest) GetCustomerCost() float64 {
	if x != nil && x.CustomerCost != nil {
		return *x.CustomerCost
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_oms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_oms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_oms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_oms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByOrderRequest) Reset() {
	*x = GetByOrderRequest{}
	mi := &file_oms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByOrderRequest) ProtoMessage() {}

func (x *GetByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetByOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{7}
}

func (x *GetByOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,4,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	OrderCost     float64                `protobuf:"fixed64,5,opt,name=order_cost,json=orderCost,proto3" json:"order_cost,omitempty"`
	Status        OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=oms.OrderStatus" json:"status,omitempty"`
	CreationDate  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	FinishDate    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finish_date,json=finishDate,proto3" json:"finish_date,omitempty"`
	Products      []*OrderProduct        `protobuf:"bytes,9,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_oms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Order) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *Order) GetOrderCost() float64 {
	if x != nil {
		return x.OrderCost
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_NEW
}

func (x *Order) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Order) GetFinishDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishDate
	}
	return nil
}

func (x *Order) GetProducts() []*OrderProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type OrderProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   string                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	OrderUuid     string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	ResultPrice   float64                `protobuf:"fixed64,3,opt,name=result_price,json=resultPrice,proto3" json:"result_price,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Product       *Product               `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProduct) Reset() {
	*x = OrderProduct{}
	mi := &file_oms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProduct) ProtoMessage() {}

func (x *OrderProduct) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProduct.ProtoReflect.Descriptor instead.
func (*OrderProduct) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{9}
}

func (x *OrderProduct) GetProductUuid() string {
	if x != nil {
		return x.ProductUuid
	}
	return ""
}

func (x *OrderProduct) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderProduct) GetResultPrice() float64 {
	if x != nil {
		return x.ResultPrice
	}
	return 0
}

func (x *OrderProduct) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderProduct) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       string                 `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Products      []*OrderProductInput   `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_oms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrderRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *CreateOrderRequest) GetProducts() []*OrderProductInput {
	if x != nil {
		return x.Products
	}
	return nil
}

type OrderProductInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   string                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProductInput) Reset() {
	*x = OrderProductInput{}
	mi := &file_oms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProductInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductInput) ProtoMessage() {}

func (x *OrderProductInput) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductInput.ProtoReflect.Descriptor instead.
func (*OrderProductInput) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{11}
}

func (x *OrderProductInput) GetProductUuid() string {
	if x != nil {
		return x.ProductUuid
	}
	return ""
}

func (x *OrderProductInput) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_oms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ListOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=oms.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_oms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrderRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrderRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_NEW
}

type ListOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResponse) Reset() {
	*x = ListOrderResponse{}
	mi := &file_oms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResponse) ProtoMessage() {}

func (x *ListOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResponse.ProtoReflect.Descriptor instead.
func (*ListOrderResponse) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrderResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Status        *OrderStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=oms.OrderStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_oms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateOrderRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateOrderRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *UpdateOrderRequest) GetStatus() OrderStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OrderStatus_NEW
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_oms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteOrderRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_oms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_oms_proto_rawDescGZIP(), []int{17}
}

func (x *GetProductsRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

var File_oms_proto protoreflect.FileDescriptor

const file_oms_proto_rawDesc = "" +
	"\n" +
	"\toms.proto\x12\x03oms\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xef\x01\n" +
	"\aProduct\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fproduct_code\x18\x03 \x01(\tR\vproductCode\x12#\n" +
	"\rcustomer_cost\x18\x04 \x01(\x01R\fcustomerCost\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"k\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fproduct_code\x18\x02 \x01(\tR\vproductCode\x12#\n" +
	"\rcustomer_cost\x18\x03 \x01(\x01R\fcustomerCost\"\xba\x01\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\fproduct_code\x18\x03 \x01(\tH\x01R\vproductCode\x88\x01\x01\x12(\n" +
	"\rcustomer_cost\x18\x04 \x01(\x01H\x02R\fcustomerCost\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_product_codeB\x10\n" +
	"\x0e_customer_cost\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"8\n" +
	"\fListResponse\x12(\n" +
	"\bproducts\x18\x01 \x03(\v2\f.oms.ProductR\bproducts\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"2\n" +
	"\x11GetByOrderRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\"\xdf\x02\n" +
	"\x05Order\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bstaff_id\x18\x04 \x01(\tR\astaffId\x12\x1d\n" +
	"\n" +
	"order_cost\x18\x05 \x01(\x01R\torderCost\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.oms.OrderStatusR\x06status\x12?\n" +
	"\rcreation_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12;\n" +
	"\vfinish_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishDate\x12-\n" +
	"\bproducts\x18\t \x03(\v2\x11.oms.OrderProductR\bproducts\"\xb3\x01\n" +
	"\fOrderProduct\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\tR\vproductUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12!\n" +
	"\fresult_price\x18\x03 \x01(\x01R\vresultPrice\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12&\n" +
	"\aproduct\x18\x05 \x01(\v2\f.oms.ProductR\aproduct\"\x96\x01\n" +
	"\x12CreateOrderRequest\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bstaff_id\x18\x03 \x01(\tR\astaffId\x122\n" +
	"\bproducts\x18\x04 \x03(\v2\x16.oms.OrderProductInputR\bproducts\"N\n" +
	"\x11OrderProductInput\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\tR\vproductUuid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"%\n" +
	"\x0fGetOrderRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"j\n" +
	"\x10ListOrderRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.oms.OrderStatusR\x06status\"7\n" +
	"\x11ListOrderResponse\x12\"\n" +
	"\x06orders\x18\x01 \x03(\v2\n" +
	".oms.OrderR\x06orders\"\x8d\x01\n" +
	"\x12UpdateOrderRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.oms.OrderStatusH\x01R\x06status\x88\x01\x01B\n" +
	"\n" +
	"\b_commentB\t\n" +
	"\a_status\"(\n" +
	"\x12DeleteOrderRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"3\n" +
	"\x12GetProductsRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid*D\n" +
	"\vOrderStatus\x12\a\n" +
	"\x03NEW\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x032\xaa\x02\n" +
	"\x0eProductService\x12*\n" +
	"\x06Create\x12\x12.oms.CreateRequest\x1a\f.oms.Product\x12$\n" +
	"\x03Get\x12\x0f.oms.GetRequest\x1a\f.oms.Product\x12+\n" +
	"\x04List\x12\x10.oms.ListRequest\x1a\x11.oms.ListResponse\x12*\n" +
	"\x06Update\x12\x12.oms.UpdateRequest\x1a\f.oms.Product\x124\n" +
	"\x06Delete\x12\x12.oms.DeleteRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\n" +
	"GetByOrder\x12\x16.oms.GetByOrderRequest\x1a\x11.oms.ListResponse2\xc2\x02\n" +
	"\fOrderService\x12-\n" +
	"\x06Create\x12\x17.oms.CreateOrderRequest\x1a\n" +
	".oms.Order\x12'\n" +
	"\x03Get\x12\x14.oms.GetOrderRequest\x1a\n" +
	".oms.Order\x125\n" +
	"\x04List\x12\x15.oms.ListOrderRequest\x1a\x16.oms.ListOrderResponse\x12-\n" +
	"\x06Update\x12\x17.oms.UpdateOrderRequest\x1a\n" +
	".oms.Order\x129\n" +
	"\x06Delete\x12\x17.oms.DeleteOrderRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\vGetProducts\x12\x17.oms.GetProductsRequest\x1a\x11.oms.ListResponseB'Z%github.com/igntnk/stocky-oms/proto/pbb\x06proto3"

var (
	file_oms_proto_rawDescOnce sync.Once
	file_oms_proto_rawDescData []byte
)

func file_oms_proto_rawDescGZIP() []byte {
	file_oms_proto_rawDescOnce.Do(func() {
		file_oms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oms_proto_rawDesc), len(file_oms_proto_rawDesc)))
	})
	return file_oms_proto_rawDescData
}

var file_oms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oms_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_oms_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: oms.OrderStatus
	(*Product)(nil),               // 1: oms.Product
	(*CreateRequest)(nil),         // 2: oms.CreateRequest
	(*UpdateRequest)(nil),         // 3: oms.UpdateRequest
	(*GetRequest)(nil),            // 4: oms.GetRequest
	(*ListRequest)(nil),           // 5: oms.ListRequest
	(*ListResponse)(nil),          // 6: oms.ListResponse
	(*DeleteRequest)(nil),         // 7: oms.DeleteRequest
	(*GetByOrderRequest)(nil),     // 8: oms.GetByOrderRequest
	(*Order)(nil),                 // 9: oms.Order
	(*OrderProduct)(nil),          // 10: oms.OrderProduct
	(*CreateOrderRequest)(nil),    // 11: oms.CreateOrderRequest
	(*OrderProductInput)(nil),     // 12: oms.OrderProductInput
	(*GetOrderRequest)(nil),       // 13: oms.GetOrderRequest
	(*ListOrderRequest)(nil),      // 14: oms.ListOrderRequest
	(*ListOrderResponse)(nil),     // 15: oms.ListOrderResponse
	(*UpdateOrderRequest)(nil),    // 16: oms.UpdateOrderRequest
	(*DeleteOrderRequest)(nil),    // 17: oms.DeleteOrderRequest
	(*GetProductsRequest)(nil),    // 18: oms.GetProductsRequest
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_oms_proto_depIdxs = []int32{
	19, // 0: oms.Product.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: oms.Product.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: oms.ListResponse.products:type_name -> oms.Product
	0,  // 3: oms.Order.status:type_name -> oms.OrderStatus
	19, // 4: oms.Order.creation_date:type_name -> google.protobuf.Timestamp
	19, // 5: oms.Order.finish_date:type_name -> google.protobuf.Timestamp
	10, // 6: oms.Order.products:type_name -> oms.OrderProduct
	1,  // 7: oms.OrderProduct.product:type_name -> oms.Product
	12, // 8: oms.CreateOrderRequest.products:type_name -> oms.OrderProductInput
	0,  // 9: oms.ListOrderRequest.status:type_name -> oms.OrderStatus
	9,  // 10: oms.ListOrderResponse.orders:type_name -> oms.Order
	0,  // 11: oms.UpdateOrderRequest.status:type_name -> oms.OrderStatus
	2,  // 12: oms.ProductService.Create:input_type -> oms.CreateRequest
	4,  // 13: oms.ProductService.Get:input_type -> oms.GetRequest
	5,  // 14: oms.ProductService.List:input_type -> oms.ListRequest
	3,  // 15: oms.ProductService.Update:input_type -> oms.UpdateRequest
	7,  // 16: oms.ProductService.Delete:input_type -> oms.DeleteRequest
	8,  // 17: oms.ProductService.GetByOrder:input_type -> oms.GetByOrderRequest
	11, // 18: oms.OrderService.Create:input_type -> oms.CreateOrderRequest
	13, // 19: oms.OrderService.Get:input_type -> oms.GetOrderRequest
	14, // 20: oms.OrderService.List:input_type -> oms.ListOrderRequest
	16, // 21: oms.OrderService.Update:input_type -> oms.UpdateOrderRequest
	17, // 22: oms.OrderService.Delete:input_type -> oms.DeleteOrderRequest
	18, // 23: oms.OrderService.GetProducts:input_type -> oms.GetProductsRequest
	1,  // 24: oms.ProductService.Create:output_type -> oms.Product
	1,  // 25: oms.ProductService.Get:output_type -> oms.Product
	6,  // 26: oms.ProductService.List:output_type -> oms.ListResponse
	1,  // 27: oms.ProductService.Update:output_type -> oms.Product
	20, // 28: oms.ProductService.Delete:output_type -> google.protobuf.Empty
	6,  // 29: oms.ProductService.GetByOrder:output_type -> oms.ListResponse
	9,  // 30: oms.OrderService.Create:output_type -> oms.Order
	9,  // 31: oms.OrderService.Get:output_type -> oms.Order
	15, // 32: oms.OrderService.List:output_type -> oms.ListOrderResponse
	9,  // 33: oms.OrderService.Update:output_type -> oms.Order
	20, // 34: oms.OrderService.Delete:output_type -> google.protobuf.Empty
	6,  // 35: oms.OrderService.GetProducts:output_type -> oms.ListResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_oms_proto_init() }
func file_oms_proto_init() {
	if File_oms_proto != nil {
		return
	}
	file_oms_proto_msgTypes[2].OneofWrappers = []any{}
	file_oms_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_proto_rawDesc), len(file_oms_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_oms_proto_goTypes,
		DependencyIndexes: file_oms_proto_depIdxs,
		EnumInfos:         file_oms_proto_enumTypes,
		MessageInfos:      file_oms_proto_msgTypes,
	}.Build()
	File_oms_proto = out.File
	file_oms_proto_goTypes = nil
	file_oms_proto_depIdxs = nil
}
